# Generated by Django 5.0.4 on 2024-05-28 01:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0002_author_user_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='default_image_blog', upload_to='images/'),
        ),
    ]
